### ISSUE TITLE
Question about the reproduced U2PL

### ISSUE THREAD

**Issue by Hugo-cell111** [ZhenZHAO/AugSeg#2]
Hi! I just read the paper of AugSeg and find a statement "Since U2PL prioritizes selecting high-quality labels from classic VOCs for testing on blender VOC, we reproduce the supervised baseline and its performance on ResNet-50 for fair comparisons". Could I ask what does it mean? Where has indicated the fact that U2PL prioritizes selecting high-quality labels? Thanks a lot!

**Comment by ZhenZHAO** [comment]
I found I;d already put the link in the footnote of page 6, Please refer to https://github.com/Haochen-Wang409/U2PL/issues/3. You can also check the split and examine the supervised baseline by yourself. Since the output stride of U2PL is 8, you might get ever higher results of these supervised baselines.
